name: CI/CD

on:
  push:
    branches:
      - develop
      - testing
      - jlpa

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codee
        uses: actions/checkout@v2

      - name: Set environment variable based on branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
            echo "ENVIRONMENT_NAME=develop" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/testing' ]]; then
            echo "ENVIRONMENT_NAME=testing" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
          
      - name: Build Docker image
        run: docker build -t n5test .

      - name: Tag Docker image
        run: docker tag n5test:latest 223964170867.dkr.ecr.us-east-1.amazonaws.com/n5test:latest

      - name: Push Docker image to AWS ECR
        run: docker push 223964170867.dkr.ecr.us-east-1.amazonaws.com/n5test:latest
