name: CI/CD

on:
  push:
    branches:
      - develop
      - testing

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set environment variable based on branch
        run: |
          if [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
            echo "ENVIRONMENT_NAME=develop" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/testing' ]]; then
            echo "ENVIRONMENT_NAME=testing" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -t n5-test .

      - name: Tag Docker image
        run: docker tag your-image-name:latest public.ecr.aws/w6r4j2i8/n5-test-public/n5-test:latest

      - name: Push Docker image to AWS ECR
        run: docker push public.ecr.aws/w6r4j2i8/n5-test-public/n5-test:latest
